# TURN API KEYS INTO CONSTANTS IN THIS FILE
GOOGLE_CLIENT_ID = ENV["LORIOUS_GOOGLE_ID"]
GOOGLE_CLIENT_SECRET = ENV["LORIOUS_GOOGLE_SECRET"]
GOOGLE_OAUTH_PATH = "/auth/google_oauth2"

Stripe.api_key = ENV["LORIOUS_STRIPE_SECRET_KEY"]
STRIPE_PUBLIC_KEY = ENV["LORIOUS_STRIPE_PUBLIC_KEY"]
