# TURN API KEYS INTO CONSTANTS IN THIS FILE
GOOGLE_KEY = ENV["LORIOUS_GOOGLE_KEY"]
GOOGLE_SECRET = ENV["LORIOUS_GOOGLE_SECRET"]
GOOGLE_APP_ID = ENV["LORIOUS_GOOGLE_APP_ID"]
GOOGLE_OAUTH_PATH = "/auth/google_oauth2"
