# COPY THIS FILE WITH VALUES INTO config/application.yml
# ======================================================

MAILCHIMP_API_KEY: # VALUE GOES HERE
MAILCHIMP_LIST_ID: # VALUE GOES HERE

MANDRILL_USERNAME: # VALUE GOES HERE
MANDRILL_API_KEY: # VALUE GOES HERE

OPENTOK_URL: # VALUE GOES HERE
OPENTOK_API_KEY: # VALUE GOES HERE
OPENTOK_API_SECRET: # VALUE GOES HERE

AWS_BUCKET_NAME: # VALUE GOES HERE
AWS_ACCESS_KEY_ID: # VALUE GOES HERE
AWS_SECRET_ACCESS_KEY: # VALUE GOES HERE

STRIPE_PUBLISHABLE_KEY: # VALUE GOES HERE
STRIPE_SECRET_KEY: # VALUE GOES HERE

GOOGLE_OAUTH2_CLIENT_ID: # VALUE GOES HERE
GOOGLE_OAUTH2_CLIENT_SECRET: # VALUE GOES HERE
GOOGLE_API_KEY: # VALUE GOES HERE

TWITTER_CONSUMER_KEY: # VALUE GOES HERE
TWITTER_CONSUMER_SECRET: # VALUE GOES HERE
TWITTER_ACCESS_TOKEN: # VALUE GOES HERE
TWITTER_ACCESS_TOKEN_SECRET: # VALUE GOES HERE

LINKEDIN_API_KEY: # VALUE GOES HERE
LINKEDIN_SECRET_KEY: # VALUE GOES HERE
LINKEDIN_OAUTH_USER_TOKEN: # VALUE GOES HERE
LINKEDIN_OAUTH_USER_SECRET: # VALUE GOES HERE

development:
  LOCATION: # VALUE GOES HERE

production:
  LOCATION: # VALUE GOES HERE

staging:
  LOCATION: # VALUE GOES HERE

beta:
  LOCATION: # VALUE GOES HERE
